#!/bin/bash
rb=../../../ircd-ratbox-ircnet/ircd
in=../../../irc2.11.2p2/x86_64-unknown-linux-gnu/ircd


for i in *.rbi.conf; do $rb -configfile `pwd`/$i -pidfile $i.pidi; done
for i in *.211.*.conf; do $in -f $i; done
