/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "../include/patchlevel.h"
#include "../include/serno.h"

const char *generation = "9";
const char *platform = "Linux life.fr.eu.umbrellix.tk 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux";
const char *ircd_version = PATCHLEVEL;
const char *serno = SERIALNUM;
const char *creation = "Tue May 19 2015 at 20:18:45 BST";

const char *infotext[] =
{
  "ircd-ratbox --",
  "Based on the original code written by Jarkko Oikarinen",
  "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
  "Copyright (c) 1996-2001 Hybrid Development Team", 
  "Copyright (c) 2002-2008 ircd-ratbox Development Team",
  "",
  "This program is free software; you can redistribute it and/or",
  "modify it under the terms of the GNU General Public License as",
  "published by the Free Software Foundation; either version 2, or",
  "(at your option) any later version.",
  "",
  " ",
  "ircd-ratbox is an evolution where ircd-hybrid left off around version 7-rc1.  ",
  "Currently the ircd-ratbox team consists of the following developers:",
  " ",
  "AndroSyn, Aaron Sethman <androsyn -at- ratbox.org>",
  "anfl, Lee Hardy <lee -at- leeh.co.uk>",
  "jilles, Jilles Tjoelker <jilles -at- stack.nl>",
  "Special thanks for support, code and ideas to:",
  "Hwy, W. Campbell <wcampbel -at- botbay.net>",
  "larne, Edward Brocklesby <ejb -at- sdf.lonestar.org>",
  " ",
  "Of course our work is based on the work of many, many others over the past",
  "10 or so years since irc has existed, including the work done by the Hybrid",
  "team, our thanks goes to them.",
  " ",
  "",
  0,
};
